### ISSUE TITLE
Cleaning crowdloan contribution data

### ISSUE THREAD

**Issue by RuchiRay** [Polkadex-Substrate/polkadex-business-website#107]
### Description

- We have received the crowdloan data from multiple places , from exchanges , partners, etc.
- All this data is in different file and there are duplicate data as well.
-  Some of the parameters are also missing

### Task

- [x] Merge the duplicate entries into one
- [x] Combine all the files into one
- [x] Calculate and add other parameters

### Sheet
[crowdloan1.csv](https://github.com/Polkadex-Substrate/polkadex-business-website/files/11634561/crowdloan1.csv)

### final sheet
[finalCrowdloan.csv](https://github.com/Polkadex-Substrate/polkadex-business-website/files/11634914/finalCrowdloan.csv)
